name: CI/CD Pipeline for SQL Server

on:
  push:
    branches:
      - develop
      - feature/*
  pull_request:
    branches:
      - main
      - develop

jobs:
  ci_dev:
    name: Continuous Integration for Dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Validate SQL Scripts
        run: python wait_for_sqlserver.py --validate-sql-scripts

      - name: Build and Run Dev Environment
        env:
          ENV_FILE: .env.dev
        run: |
          cp ${ENV_FILE} .env
          docker-compose -f docker-compose.yml --env-file ${ENV_FILE} up --build -d dev_sqlserver

      - name: Run Migrations in Dev
        env:
          ENV_FILE: .env.dev
        run: |
          cp ${ENV_FILE} .env
          python wait_for_sqlserver.py --migrate dev

  cd_qa:
    name: Deploy to QA with Approval
    runs-on: ubuntu-latest
    needs: ci_dev
    if: github.ref == 'refs/heads/develop'
    environment:
      name: QA
      url: http://qa.sqlserver
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build and Run QA Environment
        env:
          ENV_FILE: .env.qa
        run: |
          cp ${ENV_FILE} .env
          docker-compose -f docker-compose.yml --env-file ${ENV_FILE} up --build -d qa_sqlserver

      - name: Run Migrations in QA
        env:
          ENV_FILE: .env.qa
        run: |
          cp ${ENV_FILE} .env
          python wait_for_sqlserver.py --migrate qa

      - name: Approval Required for QA Deployment
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
